### ISSUE TITLE
Publishing on PyPI

### ISSUE THREAD

**Issue by nicolaslazo** [glitzflitz/pyxorfilter#4]
Hi! I saw in your TODO that you want to publish your project on PyPI and that'd allow me to use it on Amazon EMR. I found [this tutorial](https://docs.travis-ci.com/user/deployment/pypi/#releasing-to-a-self-hosted-pypi) and theoretically this `.travis.yml` should work:
```
language: python
addons:
  apt:
    packages:
    - build-essential
python:
- 3.5
- 3.6
- 3.7
- 3.8
- nightly
- pypy3
matrix:
  fast_finish: true
  allow_failures:
  - python: nightly
install:
- pip install nose
script:
- python setup.py test
cache:
- pip
deploy:
  provider: pypi
  username: __token__
  password:
    secure: AVERYLONGSTRING
  on:
    tags: true
    branch: master
```
To get the password I used `travis encrypt pypi-api-token --add deploy.password --com` though I couldn't figure out how to publish it on TestPyPI.
